#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
#  unbenannt.py
#
#  Copyright 2012 Christian Schramm <christian.h.m.schramm@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#

import argparse

from src import commands
from src import vecoh

def main():
    parser = argparse.ArgumentParser(description='Vecoh is an xml and html revision control software.')
    subparsers = parser.add_subparsers()

    parser_init = subparsers.add_parser("init", help="initialize vecoh for this directory and subdirectories")
    parser_init.set_defaults(func=commands.init)
    parser_init.add_argument("--backend", default="file", help="the storage backend, default: file")

    parser_save = subparsers.add_parser("save", help="Save current revision of file(s)")
    parser_save.set_defaults(func=commands.save)
    parser_save.add_argument("filenames", metavar="file", nargs="+", help="the file(s) to save")
    parser_save.add_argument("--backend", default="file", help="the storage backend, default: file")
    parser_save.add_argument("--filetype", default="auto", help="the parsing method, default: auto", choices=["auto", "xml", "hmtl"])
    parser_save.add_argument("--message", "-m", default="", help="the commit message")

    parser_history = subparsers.add_parser("history", help="show history of files")
    parser_history.set_defaults(func=commands.history)
    parser_history.add_argument("filenames", metavar="file", nargs="+", help="the file(s) to inspect history")
    parser_history.add_argument("--backend", default="file", help="the storage backend, default: file")

    parser_revision = subparsers.add_parser("revision", help="set a file to a given revision")
    parser_revision.set_defaults(func=commands.revision)
    parser_revision.add_argument("filename", metavar="file", help="the file to change revision")
    parser_revision.add_argument("hash", help="the revision hash")
    parser_revision.add_argument("--backend", default="file", help="the storage backend, default: file")
    parser_revision.add_argument("--force", "-f", action="store_true", default=False, help="force setting revision")

    args = parser.parse_args()
    try:
        args.func(args)
    except vecoh.VecohError as e:
        print("\033[91m" + "Error:" + "\033[0m", e.message)

    return 0

if __name__ == '__main__':
    main()

